name: Editor compilation workflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache Cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          lib/**/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libncursesw5-dev clang

# Dependencies
    - name: Install tree-sitter CLI
      run: |
        if ! command -v tree-sitter &> /dev/null; then
          cargo install tree-sitter-cli --version 0.24.7
        fi

    - name: Building dependencies - tree-sitter
      run: sudo make -C lib/tree-sitter/ install
    

# Check project status
    - name: Compile project - building - parsers, cJSON, al.
      run: make -j2

    - name: Executing installation script
      run: |
        make install-config
        sudo make install-bin install-data
